### ISSUE TITLE
License missing 

### ISSUE THREAD

**Issue by JustAMan** [sleuth255/screenplay#4]
Could you please add some license to your project?

**Comment by sleuth255** [comment]
Sadly, this project is cloned from SimonJHogan playz emby which has no license.  I'm allowed to release this on LG TV by the author, but don't have the authority to license the code for other use.  If Simon licenses his base then I can proceed.

**Comment by JustAMan** [comment]
Thanks for the update, can you give me a way to contact original author? Maybe github repo or something?

**Comment by sleuth255** [comment]
Sure, the original repo is here on github

https://github.com/simonjhogan/playz-emby

**Comment by JustAMan** [comment]
okay, made an issue there: https://github.com/simonjhogan/playz-emby/issues/1

**Comment by anthonylavado** [comment]
I hope we can re-open this - I got in touch with Simon and he’s given us explicit permission to go ahead, as long as there’s attribution. He’s got a license branch now, with the MIT license: https://github.com/simonjhogan/playz-emby/blob/add-license-1/LICENSE

**Comment by JustAMan** [comment]
Don't know about MIT, commit to `master` that adds license adds `Apache-2.0`: https://github.com/simonjhogan/playz-emby/commit/435fcba9025857d25adbde09ef3f39b6b87ee136

**Comment by anthonylavado** [comment]
@JustAMan looks like he changed his mind, and made it the same license as his PlayZ for Plex. Either way, good news!

**Comment by anthonylavado** [comment]
@sleuth255 Are you able to also provide a license as well?
